# cf http://qiita.com/pine613/items/3fdc4e1bd06065cc056d
build: off
shallow_clone: true
skip_tags: true
skip_branch_with_pr: true
init:
  - git config --global core.autocrlf input
install:
  - choco install strawberryperl
  - SET "PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%"
test_script:
  - git clone https://github.com/miyagawa/cpanminus.git
  - cd cpanminus
  - git log -1
  - cd ..
  - SET "TEST_CPANM_PATH=cpanminus\App-cpanminus\script\cpanm.PL"
  - prove t
